apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: details-cpu-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: details-v1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50